spring.application.name=Connection
Spring.datasource.url=jdbc:postgresql://localhost:5432/StudentsInfo
Spring.datasource.username=postgres
Spring.datasource.password=Evans#123
Spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true